Repository sign-muscat/sorisonsoon-front, pull requests merged in 2024-08, with the labels that each got.

#8 메인 화면 사이드바 구현
  public/images/icon_sidebar_hand.png
  public/images/icon_sidebar_lip.png
  public/images/icon_sidebar_sound.png
  public/index.html
  src/components/Header.js
  src/components/Sidebar.js
  src/layouts/MainLayout.js
  src/pages/MainPage.js
Labels: 🎨Layout

#9 #5 맞수수 화면 UI 개선
  package-lock.json
  package.json
  public/images/birthday-emoji.png
  public/images/no_smoking_2.png
  src/App.js
  src/apis/HandGameAPICalls.js
  src/apis/RankAPICalls.js
  src/apis/api.js
  src/components/button/DifficultyButton.js
  src/components/button/QuitGame.js
  src/components/button/RegistRank.js
  src/components/button/SkipButton.js
  src/components/game/GameHeader.js
  src/components/item/QuestionTableItem.js
  src/components/table/QuestionTable.js
  src/modules/HandGameReducer.js
  src/modules/RankReducer.js
  src/modules/index.js
  src/pages/HandGamePage.js
  src/pages/LipGameInfo.js
  src/pages/SoundGameInfo.js
  src/pages/hand/HandGameFinish.js
  src/pages/hand/HandGameHint.js
  src/pages/hand/HandGameInfo.js
  src/pages/hand/HandGamePage.js
  src/pages/hand/HandGameQuestion.js
  src/pages/hand/SuccessModal.js
  src/pages/hand/WordStepper.js
  src/store.js
  src/theme/theme.js
  src/utils/DifficultyUtils.js
  src/utils/ToastUtils.js
Labels: ✨ Feature, 🎨Layout, 🔧Refactor

#18 #17 도소탐 프론트 로직 구현
  src/apis/SoundGameAPICalls.js
  src/apis/api.js
  src/components/button/DifficultyButton.js
  src/components/item/SimilarityTableItem.js
  src/components/table/SimilarityTable.js
  src/modules/SoundGameReducer.js
  src/modules/index.js
  src/pages/sound/SoundGameAnswer.js
  src/pages/sound/SoundGameInfo.js
  src/pages/sound/SoundGamePage.js
  src/pages/sound/SoundGameQuestion.js
  src/utils/DifficultyUtils.js
Labels: ✨ Feature

#25 #24 파일 import 경로 문제 해결
  src/App.js
Labels: 🐞Bug

#30 #26 이미지 분류 모델 적용으로 인한 프론트 부분 변경
  src/apis/HandGameAPICalls.js
  src/apis/fastapi.js
  src/modules/HandGameReducer.js
  src/pages/hand/HandGamePage.js
Labels: ✨ Feature, 🔧Refactor

#31 #27 친구 관련 컴포넌트 구현
  src/apis/FriendAPICalls.js
  src/components/button/RequestFriendButton.js
  src/components/card/FriendApplyCard.js
  src/components/card/FriendCard.js
  src/modules/FriendReducer.js
  src/modules/index.js
Labels: ✨ Feature, 🎨Layout

#36 #34 도소탐 플레이 기록 저장 API 호출부 작성
  src/apis/SoundGameAPICalls.js
  src/components/button/CountdownButton.js
  src/components/game/GameHeader.js
  src/components/item/SimilarityTableItem.js
  src/modules/SoundGameReducer.js
  src/pages/hand/SuccessModal.js
  src/pages/sound/SoundGameAnswer.js
  src/pages/sound/SoundGameInfo.js
  src/pages/sound/SoundGamePage.js
  src/pages/sound/SoundSuccessModal.js
Labels: ✨ Feature, 🔧Refactor

#37 #35 맞수수 플레이 기록 저장 API 호출부 작성
  src/apis/HandGameAPICalls.js
  src/pages/hand/HandGameFinish.js
Labels: ✨ Feature, 🔧Refactor

#38 #28 친구 관련 버튼 구현
  src/components/button/CancelApplyButton.js
  src/components/card/FriendApplyCard.js
  src/components/card/RecommendFriendCard.js
Labels: ✨ Feature, 🎨Layout

#45 #44 프론트 배포를 위한 Actions 작성
  .github/workflows/push-to-deploy.yml
Labels: ⚙️Setting

#42 #1 로그인 페이지 및 관련 기능
  .gitignore
  package-lock.json
  package.json
  public/images/icon_google.png
  public/images/img_line_or.png
  public/images/img_login_banner.png
  public/images/logo.png
  public/index.html
  src/App.js
  src/apis/AuthAPICalls.js
  src/apis/api.js
  src/apis/lipGameAPICalls.js
  src/components/Header.js
  src/components/form/FindPasswordForm.js
  src/components/form/LoginForm.js
  src/components/router/ProtectedRoute.js
  src/components/table/LipSimilarityTable.js
  src/layouts/MainLayout.js
  src/modules/AuthModules.js
  src/modules/index.js
  src/pages/auth/FindPasswordPage.js
  src/pages/auth/LoginPage.js
  src/pages/lip/LipGameAnswer.js
  src/pages/lip/LipGameInfo.js
  src/pages/lip/LipGamePage.js
  src/pages/lip/SuccessModal.js
  src/theme/theme.js
  src/utils/AlertDialogUtils.js
  src/utils/TokenUtils.js
Labels: ✨ Feature, 🎨Layout

#33 #32 myPage main layout
  .env
  package-lock.json
  package.json
  src/App.js
  src/pages/MainPage.js
  src/pages/myPage/DashboardSection.js
  src/pages/myPage/GuestBookSection.js
  src/pages/myPage/MedalSection.js
  src/pages/myPage/MypageHomePage.js
  src/pages/myPage/ProfileSection.js
  src/pages/myPage/QuestSection.js
  src/pages/myPage/RankingSection.js
  src/pages/myPage/WordCloudSection.js
  src/pages/users/EditUsersInfo.js
  src/pages/users/SignUp.js
  src/pages/users/SuccessPage.js
  src/pages/users/Withdraw.js
Labels: ✨ Feature

#40 #39 guest book layout
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/ScrollTop.js
  src/components/form/LoginForm.js
  src/index.js
  src/pages/myPage/MypageHomePage.js
  src/pages/myPage/ProfileSection.js
  src/pages/myPage/WordCloudSection.js
  src/pages/myPage/dashboard/DashboardSection.js
  src/pages/myPage/guestBook/CreateGuestBook.js
  src/pages/myPage/guestBook/GuestBookList.js
  src/pages/myPage/guestBook/GuestBookSection.js
  src/pages/pricing/PricingPage.js
  src/pages/users/EditUsersInfo.js
  src/pages/users/SignUp.js
  src/pages/users/SuccessPage.js
  src/pages/users/Withdraw.js
Labels: 🎨Layout

#47 #46 맞수수 가이드 이미지 오류 해결 및 도소탐 제출 기능 수정
  .github/workflows/push-to-deploy.yml
  package-lock.json
  package.json
  src/App.js
  src/apis/SoundGameAPICalls.js
  src/index.js
  src/modules/HandGameReducer.js
  src/modules/SoundGameReducer.js
  src/modules/index.js
  src/pages/MainPage.js
  src/pages/hand/HandGamePage.js
  src/pages/sound/SoundGameAnswer.js
  src/pages/sound/SoundGameInfo.js
  src/pages/sound/SoundGamePage.js
Labels: ✨ Feature, 🐞Bug

#50 feat: S3Bucket-connect
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/apis/FriendAPICalls.js
  src/apis/HandGameAPICalls.js
  src/apis/SoundGameAPICalls.js
  src/apis/api.js
  src/apis/fastapi.js
  src/components/Header.js
  src/components/form/SignUpForm.js
  src/pages/lip/LipGameQuestion.js
  src/pages/myPage/DashboardSection.js
  src/pages/myPage/GuestBookSection.js
  src/pages/myPage/MypageHomePage.js
  src/pages/myPage/WordCloudSection.js
  src/pages/myPage/dashboard/DashBoardGraph.js
  src/pages/myPage/dashboard/DashBoardSection.js
  src/pages/myPage/dashboard/DashboardSection.js
  src/pages/myPage/friend/FriendSection.js
  src/pages/myPage/guestBook/CreateGuestBook.js
  src/pages/myPage/guestBook/GuestBookList.js
  src/pages/myPage/guestBook/GuestBookSection.js
  src/pages/myPage/medal/MedalSection.js
  src/pages/myPage/profile/ProfileSection.js
  src/pages/myPage/ranking/RankingSection.js
  src/pages/myPage/wordCloud/WordCloudSection.js
  src/pages/pricing/PricingPage.js
  src/pages/sound/SoundGameAnswer.js
  src/pages/sound/SoundGameInfo.js
  src/pages/users/EditUsersInfo.js
  src/pages/users/SignUp.js
  src/pages/users/SignUpPage.js
  src/pages/users/SuccessPage.js
  src/pages/users/Withdraw.js
Labels: ✨ Feature

#52 #51 통합 작업 및 기능 추가
  .env
  package-lock.json
  package.json
  public/images/icon_more_btn.png
  public/images/icon_user.png
  public/images/img_banner_1.png
  public/images/img_banner_2.png
  public/index.html
  src/apis/RankAPICalls.js
  src/components/card/GameCard.js
  src/components/form/LoginForm.js
  src/components/temporary/Banner.js
  src/components/temporary/MainRanking.js
  src/components/temporary/MainTableList.js
  src/components/temporary/MainUserInfo.js
  src/components/temporary/MyPageRanking.js
  src/modules/RankReducer.js
  src/pages/MainPage.js
  src/pages/lip/LipGameAnswer.js
  src/pages/lip/LipGameFinish.js
  src/pages/lip/LipGameHint.js
  src/pages/lip/LipGamePage.js
  src/pages/myPage/ranking/RankingSection.js
Labels: ✨ Feature, 🎨Layout, 🔧Refactor

#54 #51 마지막 수정
  .env
  src/components/Header.js
  src/components/card/GameCard.js
  src/components/temporary/MainUserInfo.js
  src/layouts/MainLayout.js
  src/pages/lip/LipGameInfo.js
  src/pages/lip/LipGamePage.js
  src/pages/lip/LipGameQuestion.js
  src/pages/lip/SuccessModal.js
Labels: 🎨Layout, 🐞Bug, 🔧Refactor
